name: bennu-image-build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sandialabs/sceptre-phenix/phenix:main
      options: --privileged # needed for kernel device-mapper permissions

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: bennu image build
        run: |
          phenix version
          mkdir out
          phenix image create -O ./overlays/bennu,./overlays/brash -T ./scripts/aptly,./scripts/bennu --format qcow2 --release focal -c bennu --size 10G
          phenix image build bennu -o ./out -x

      # upload bennu qc2 as artifact
      - name: upload qc2
        uses: actions/upload-artifact@v4
        with:
          name: bennu.qc2
          path: ./out/bennu.qc2         
